// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: education.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Education struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Program       string                 `protobuf:"bytes,4,opt,name=program,proto3" json:"program,omitempty"`
	University    string                 `protobuf:"bytes,5,opt,name=university,proto3" json:"university,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Education) Reset() {
	*x = Education{}
	mi := &file_education_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Education) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Education) ProtoMessage() {}

func (x *Education) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Education.ProtoReflect.Descriptor instead.
func (*Education) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{0}
}

func (x *Education) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Education) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Education) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Education) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *Education) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

type CreateEducationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Program       string                 `protobuf:"bytes,3,opt,name=program,proto3" json:"program,omitempty"`
	University    string                 `protobuf:"bytes,4,opt,name=university,proto3" json:"university,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEducationRequest) Reset() {
	*x = CreateEducationRequest{}
	mi := &file_education_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEducationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEducationRequest) ProtoMessage() {}

func (x *CreateEducationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEducationRequest.ProtoReflect.Descriptor instead.
func (*CreateEducationRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEducationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateEducationRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CreateEducationRequest) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *CreateEducationRequest) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

type GetEducationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEducationRequest) Reset() {
	*x = GetEducationRequest{}
	mi := &file_education_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEducationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEducationRequest) ProtoMessage() {}

func (x *GetEducationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEducationRequest.ProtoReflect.Descriptor instead.
func (*GetEducationRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{2}
}

func (x *GetEducationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEducationsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEducationsByUserRequest) Reset() {
	*x = GetEducationsByUserRequest{}
	mi := &file_education_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEducationsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEducationsByUserRequest) ProtoMessage() {}

func (x *GetEducationsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEducationsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetEducationsByUserRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{3}
}

func (x *GetEducationsByUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateEducationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Program       string                 `protobuf:"bytes,3,opt,name=program,proto3" json:"program,omitempty"`
	University    string                 `protobuf:"bytes,4,opt,name=university,proto3" json:"university,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEducationRequest) Reset() {
	*x = UpdateEducationRequest{}
	mi := &file_education_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEducationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEducationRequest) ProtoMessage() {}

func (x *UpdateEducationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEducationRequest.ProtoReflect.Descriptor instead.
func (*UpdateEducationRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEducationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEducationRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *UpdateEducationRequest) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *UpdateEducationRequest) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

type DeleteEducationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEducationRequest) Reset() {
	*x = DeleteEducationRequest{}
	mi := &file_education_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEducationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEducationRequest) ProtoMessage() {}

func (x *DeleteEducationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEducationRequest.ProtoReflect.Descriptor instead.
func (*DeleteEducationRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEducationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteEducationsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEducationsByUserRequest) Reset() {
	*x = DeleteEducationsByUserRequest{}
	mi := &file_education_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEducationsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEducationsByUserRequest) ProtoMessage() {}

func (x *DeleteEducationsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEducationsByUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteEducationsByUserRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEducationsByUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type EmptyEducationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyEducationResponse) Reset() {
	*x = EmptyEducationResponse{}
	mi := &file_education_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyEducationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyEducationResponse) ProtoMessage() {}

func (x *EmptyEducationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyEducationResponse.ProtoReflect.Descriptor instead.
func (*EmptyEducationResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{7}
}

type ListEducationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Educations    []*Education           `protobuf:"bytes,1,rep,name=educations,proto3" json:"educations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEducationsResponse) Reset() {
	*x = ListEducationsResponse{}
	mi := &file_education_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEducationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEducationsResponse) ProtoMessage() {}

func (x *ListEducationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEducationsResponse.ProtoReflect.Descriptor instead.
func (*ListEducationsResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{8}
}

func (x *ListEducationsResponse) GetEducations() []*Education {
	if x != nil {
		return x.Educations
	}
	return nil
}

var File_education_proto protoreflect.FileDescriptor

const file_education_proto_rawDesc = "" +
	"\n" +
	"\x0feducation.proto\x12\x02pb\"\x84\x01\n" +
	"\tEducation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\aprogram\x18\x04 \x01(\tR\aprogram\x12\x1e\n" +
	"\n" +
	"university\x18\x05 \x01(\tR\n" +
	"university\"\x81\x01\n" +
	"\x16CreateEducationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\aprogram\x18\x03 \x01(\tR\aprogram\x12\x1e\n" +
	"\n" +
	"university\x18\x04 \x01(\tR\n" +
	"university\"%\n" +
	"\x13GetEducationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\x1aGetEducationsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"x\n" +
	"\x16UpdateEducationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\aprogram\x18\x03 \x01(\tR\aprogram\x12\x1e\n" +
	"\n" +
	"university\x18\x04 \x01(\tR\n" +
	"university\"(\n" +
	"\x16DeleteEducationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\x1dDeleteEducationsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x18\n" +
	"\x16EmptyEducationResponse\"G\n" +
	"\x16ListEducationsResponse\x12-\n" +
	"\n" +
	"educations\x18\x01 \x03(\v2\r.pb.EducationR\n" +
	"educations2\xbd\x03\n" +
	"\x10EducationService\x12<\n" +
	"\x0fCreateEducation\x12\x1a.pb.CreateEducationRequest\x1a\r.pb.Education\x126\n" +
	"\fGetEducation\x12\x17.pb.GetEducationRequest\x1a\r.pb.Education\x12Q\n" +
	"\x13GetEducationsByUser\x12\x1e.pb.GetEducationsByUserRequest\x1a\x1a.pb.ListEducationsResponse\x12<\n" +
	"\x0fUpdateEducation\x12\x1a.pb.UpdateEducationRequest\x1a\r.pb.Education\x12I\n" +
	"\x0fDeleteEducation\x12\x1a.pb.DeleteEducationRequest\x1a\x1a.pb.EmptyEducationResponse\x12W\n" +
	"\x16DeleteEducationsByUser\x12!.pb.DeleteEducationsByUserRequest\x1a\x1a.pb.EmptyEducationResponseB\x16Z\x14education-service/pbb\x06proto3"

var (
	file_education_proto_rawDescOnce sync.Once
	file_education_proto_rawDescData []byte
)

func file_education_proto_rawDescGZIP() []byte {
	file_education_proto_rawDescOnce.Do(func() {
		file_education_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_education_proto_rawDesc), len(file_education_proto_rawDesc)))
	})
	return file_education_proto_rawDescData
}

var file_education_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_education_proto_goTypes = []any{
	(*Education)(nil),                     // 0: pb.Education
	(*CreateEducationRequest)(nil),        // 1: pb.CreateEducationRequest
	(*GetEducationRequest)(nil),           // 2: pb.GetEducationRequest
	(*GetEducationsByUserRequest)(nil),    // 3: pb.GetEducationsByUserRequest
	(*UpdateEducationRequest)(nil),        // 4: pb.UpdateEducationRequest
	(*DeleteEducationRequest)(nil),        // 5: pb.DeleteEducationRequest
	(*DeleteEducationsByUserRequest)(nil), // 6: pb.DeleteEducationsByUserRequest
	(*EmptyEducationResponse)(nil),        // 7: pb.EmptyEducationResponse
	(*ListEducationsResponse)(nil),        // 8: pb.ListEducationsResponse
}
var file_education_proto_depIdxs = []int32{
	0, // 0: pb.ListEducationsResponse.educations:type_name -> pb.Education
	1, // 1: pb.EducationService.CreateEducation:input_type -> pb.CreateEducationRequest
	2, // 2: pb.EducationService.GetEducation:input_type -> pb.GetEducationRequest
	3, // 3: pb.EducationService.GetEducationsByUser:input_type -> pb.GetEducationsByUserRequest
	4, // 4: pb.EducationService.UpdateEducation:input_type -> pb.UpdateEducationRequest
	5, // 5: pb.EducationService.DeleteEducation:input_type -> pb.DeleteEducationRequest
	6, // 6: pb.EducationService.DeleteEducationsByUser:input_type -> pb.DeleteEducationsByUserRequest
	0, // 7: pb.EducationService.CreateEducation:output_type -> pb.Education
	0, // 8: pb.EducationService.GetEducation:output_type -> pb.Education
	8, // 9: pb.EducationService.GetEducationsByUser:output_type -> pb.ListEducationsResponse
	0, // 10: pb.EducationService.UpdateEducation:output_type -> pb.Education
	7, // 11: pb.EducationService.DeleteEducation:output_type -> pb.EmptyEducationResponse
	7, // 12: pb.EducationService.DeleteEducationsByUser:output_type -> pb.EmptyEducationResponse
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_education_proto_init() }
func file_education_proto_init() {
	if File_education_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_education_proto_rawDesc), len(file_education_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_education_proto_goTypes,
		DependencyIndexes: file_education_proto_depIdxs,
		MessageInfos:      file_education_proto_msgTypes,
	}.Build()
	File_education_proto = out.File
	file_education_proto_goTypes = nil
	file_education_proto_depIdxs = nil
}
