syntax = "proto3";

package pb;

option go_package = "education-service/pb";

message Education {
  int64 id = 1;
  int64 user_id = 2;
  string level = 3;
  string program = 4;
  string university = 5;
}

message CreateEducationRequest { int64 user_id = 1; string level = 2; string program = 3; string university = 4; }
message GetEducationRequest { int64 id = 1; }
message GetEducationsByUserRequest { int64 user_id = 1; }
message UpdateEducationRequest { int64 id = 1; string level = 2; string program = 3; string university = 4; }
message DeleteEducationRequest { int64 id = 1; }
message DeleteEducationsByUserRequest { int64 user_id = 1; }
message EmptyEducationResponse {}

message ListEducationsResponse {
  repeated Education educations = 1;
}

service EducationService {
  rpc CreateEducation(CreateEducationRequest) returns (Education);
  rpc GetEducation(GetEducationRequest) returns (Education);
  rpc GetEducationsByUser(GetEducationsByUserRequest) returns (ListEducationsResponse);
  rpc UpdateEducation(UpdateEducationRequest) returns (Education);
  rpc DeleteEducation(DeleteEducationRequest) returns (EmptyEducationResponse);
  rpc DeleteEducationsByUser(DeleteEducationsByUserRequest) returns (EmptyEducationResponse);
}