// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: education.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	pb "user-service/pb"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EducationServiceName is the fully-qualified name of the EducationService service.
	EducationServiceName = "pb.EducationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EducationServiceCreateEducationProcedure is the fully-qualified name of the EducationService's
	// CreateEducation RPC.
	EducationServiceCreateEducationProcedure = "/pb.EducationService/CreateEducation"
	// EducationServiceGetEducationProcedure is the fully-qualified name of the EducationService's
	// GetEducation RPC.
	EducationServiceGetEducationProcedure = "/pb.EducationService/GetEducation"
	// EducationServiceGetEducationsByUserProcedure is the fully-qualified name of the
	// EducationService's GetEducationsByUser RPC.
	EducationServiceGetEducationsByUserProcedure = "/pb.EducationService/GetEducationsByUser"
	// EducationServiceUpdateEducationProcedure is the fully-qualified name of the EducationService's
	// UpdateEducation RPC.
	EducationServiceUpdateEducationProcedure = "/pb.EducationService/UpdateEducation"
	// EducationServiceDeleteEducationProcedure is the fully-qualified name of the EducationService's
	// DeleteEducation RPC.
	EducationServiceDeleteEducationProcedure = "/pb.EducationService/DeleteEducation"
	// EducationServiceDeleteEducationsByUserProcedure is the fully-qualified name of the
	// EducationService's DeleteEducationsByUser RPC.
	EducationServiceDeleteEducationsByUserProcedure = "/pb.EducationService/DeleteEducationsByUser"
)

// EducationServiceClient is a client for the pb.EducationService service.
type EducationServiceClient interface {
	CreateEducation(context.Context, *connect.Request[pb.CreateEducationRequest]) (*connect.Response[pb.Education], error)
	GetEducation(context.Context, *connect.Request[pb.GetEducationRequest]) (*connect.Response[pb.Education], error)
	GetEducationsByUser(context.Context, *connect.Request[pb.GetEducationsByUserRequest]) (*connect.Response[pb.ListEducationsResponse], error)
	UpdateEducation(context.Context, *connect.Request[pb.UpdateEducationRequest]) (*connect.Response[pb.Education], error)
	DeleteEducation(context.Context, *connect.Request[pb.DeleteEducationRequest]) (*connect.Response[pb.EmptyEducationResponse], error)
	DeleteEducationsByUser(context.Context, *connect.Request[pb.DeleteEducationsByUserRequest]) (*connect.Response[pb.EmptyEducationResponse], error)
}

// NewEducationServiceClient constructs a client for the pb.EducationService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEducationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EducationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	educationServiceMethods := pb.File_education_proto.Services().ByName("EducationService").Methods()
	return &educationServiceClient{
		createEducation: connect.NewClient[pb.CreateEducationRequest, pb.Education](
			httpClient,
			baseURL+EducationServiceCreateEducationProcedure,
			connect.WithSchema(educationServiceMethods.ByName("CreateEducation")),
			connect.WithClientOptions(opts...),
		),
		getEducation: connect.NewClient[pb.GetEducationRequest, pb.Education](
			httpClient,
			baseURL+EducationServiceGetEducationProcedure,
			connect.WithSchema(educationServiceMethods.ByName("GetEducation")),
			connect.WithClientOptions(opts...),
		),
		getEducationsByUser: connect.NewClient[pb.GetEducationsByUserRequest, pb.ListEducationsResponse](
			httpClient,
			baseURL+EducationServiceGetEducationsByUserProcedure,
			connect.WithSchema(educationServiceMethods.ByName("GetEducationsByUser")),
			connect.WithClientOptions(opts...),
		),
		updateEducation: connect.NewClient[pb.UpdateEducationRequest, pb.Education](
			httpClient,
			baseURL+EducationServiceUpdateEducationProcedure,
			connect.WithSchema(educationServiceMethods.ByName("UpdateEducation")),
			connect.WithClientOptions(opts...),
		),
		deleteEducation: connect.NewClient[pb.DeleteEducationRequest, pb.EmptyEducationResponse](
			httpClient,
			baseURL+EducationServiceDeleteEducationProcedure,
			connect.WithSchema(educationServiceMethods.ByName("DeleteEducation")),
			connect.WithClientOptions(opts...),
		),
		deleteEducationsByUser: connect.NewClient[pb.DeleteEducationsByUserRequest, pb.EmptyEducationResponse](
			httpClient,
			baseURL+EducationServiceDeleteEducationsByUserProcedure,
			connect.WithSchema(educationServiceMethods.ByName("DeleteEducationsByUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// educationServiceClient implements EducationServiceClient.
type educationServiceClient struct {
	createEducation        *connect.Client[pb.CreateEducationRequest, pb.Education]
	getEducation           *connect.Client[pb.GetEducationRequest, pb.Education]
	getEducationsByUser    *connect.Client[pb.GetEducationsByUserRequest, pb.ListEducationsResponse]
	updateEducation        *connect.Client[pb.UpdateEducationRequest, pb.Education]
	deleteEducation        *connect.Client[pb.DeleteEducationRequest, pb.EmptyEducationResponse]
	deleteEducationsByUser *connect.Client[pb.DeleteEducationsByUserRequest, pb.EmptyEducationResponse]
}

// CreateEducation calls pb.EducationService.CreateEducation.
func (c *educationServiceClient) CreateEducation(ctx context.Context, req *connect.Request[pb.CreateEducationRequest]) (*connect.Response[pb.Education], error) {
	return c.createEducation.CallUnary(ctx, req)
}

// GetEducation calls pb.EducationService.GetEducation.
func (c *educationServiceClient) GetEducation(ctx context.Context, req *connect.Request[pb.GetEducationRequest]) (*connect.Response[pb.Education], error) {
	return c.getEducation.CallUnary(ctx, req)
}

// GetEducationsByUser calls pb.EducationService.GetEducationsByUser.
func (c *educationServiceClient) GetEducationsByUser(ctx context.Context, req *connect.Request[pb.GetEducationsByUserRequest]) (*connect.Response[pb.ListEducationsResponse], error) {
	return c.getEducationsByUser.CallUnary(ctx, req)
}

// UpdateEducation calls pb.EducationService.UpdateEducation.
func (c *educationServiceClient) UpdateEducation(ctx context.Context, req *connect.Request[pb.UpdateEducationRequest]) (*connect.Response[pb.Education], error) {
	return c.updateEducation.CallUnary(ctx, req)
}

// DeleteEducation calls pb.EducationService.DeleteEducation.
func (c *educationServiceClient) DeleteEducation(ctx context.Context, req *connect.Request[pb.DeleteEducationRequest]) (*connect.Response[pb.EmptyEducationResponse], error) {
	return c.deleteEducation.CallUnary(ctx, req)
}

// DeleteEducationsByUser calls pb.EducationService.DeleteEducationsByUser.
func (c *educationServiceClient) DeleteEducationsByUser(ctx context.Context, req *connect.Request[pb.DeleteEducationsByUserRequest]) (*connect.Response[pb.EmptyEducationResponse], error) {
	return c.deleteEducationsByUser.CallUnary(ctx, req)
}

// EducationServiceHandler is an implementation of the pb.EducationService service.
type EducationServiceHandler interface {
	CreateEducation(context.Context, *connect.Request[pb.CreateEducationRequest]) (*connect.Response[pb.Education], error)
	GetEducation(context.Context, *connect.Request[pb.GetEducationRequest]) (*connect.Response[pb.Education], error)
	GetEducationsByUser(context.Context, *connect.Request[pb.GetEducationsByUserRequest]) (*connect.Response[pb.ListEducationsResponse], error)
	UpdateEducation(context.Context, *connect.Request[pb.UpdateEducationRequest]) (*connect.Response[pb.Education], error)
	DeleteEducation(context.Context, *connect.Request[pb.DeleteEducationRequest]) (*connect.Response[pb.EmptyEducationResponse], error)
	DeleteEducationsByUser(context.Context, *connect.Request[pb.DeleteEducationsByUserRequest]) (*connect.Response[pb.EmptyEducationResponse], error)
}

// NewEducationServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEducationServiceHandler(svc EducationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	educationServiceMethods := pb.File_education_proto.Services().ByName("EducationService").Methods()
	educationServiceCreateEducationHandler := connect.NewUnaryHandler(
		EducationServiceCreateEducationProcedure,
		svc.CreateEducation,
		connect.WithSchema(educationServiceMethods.ByName("CreateEducation")),
		connect.WithHandlerOptions(opts...),
	)
	educationServiceGetEducationHandler := connect.NewUnaryHandler(
		EducationServiceGetEducationProcedure,
		svc.GetEducation,
		connect.WithSchema(educationServiceMethods.ByName("GetEducation")),
		connect.WithHandlerOptions(opts...),
	)
	educationServiceGetEducationsByUserHandler := connect.NewUnaryHandler(
		EducationServiceGetEducationsByUserProcedure,
		svc.GetEducationsByUser,
		connect.WithSchema(educationServiceMethods.ByName("GetEducationsByUser")),
		connect.WithHandlerOptions(opts...),
	)
	educationServiceUpdateEducationHandler := connect.NewUnaryHandler(
		EducationServiceUpdateEducationProcedure,
		svc.UpdateEducation,
		connect.WithSchema(educationServiceMethods.ByName("UpdateEducation")),
		connect.WithHandlerOptions(opts...),
	)
	educationServiceDeleteEducationHandler := connect.NewUnaryHandler(
		EducationServiceDeleteEducationProcedure,
		svc.DeleteEducation,
		connect.WithSchema(educationServiceMethods.ByName("DeleteEducation")),
		connect.WithHandlerOptions(opts...),
	)
	educationServiceDeleteEducationsByUserHandler := connect.NewUnaryHandler(
		EducationServiceDeleteEducationsByUserProcedure,
		svc.DeleteEducationsByUser,
		connect.WithSchema(educationServiceMethods.ByName("DeleteEducationsByUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pb.EducationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EducationServiceCreateEducationProcedure:
			educationServiceCreateEducationHandler.ServeHTTP(w, r)
		case EducationServiceGetEducationProcedure:
			educationServiceGetEducationHandler.ServeHTTP(w, r)
		case EducationServiceGetEducationsByUserProcedure:
			educationServiceGetEducationsByUserHandler.ServeHTTP(w, r)
		case EducationServiceUpdateEducationProcedure:
			educationServiceUpdateEducationHandler.ServeHTTP(w, r)
		case EducationServiceDeleteEducationProcedure:
			educationServiceDeleteEducationHandler.ServeHTTP(w, r)
		case EducationServiceDeleteEducationsByUserProcedure:
			educationServiceDeleteEducationsByUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEducationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEducationServiceHandler struct{}

func (UnimplementedEducationServiceHandler) CreateEducation(context.Context, *connect.Request[pb.CreateEducationRequest]) (*connect.Response[pb.Education], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.EducationService.CreateEducation is not implemented"))
}

func (UnimplementedEducationServiceHandler) GetEducation(context.Context, *connect.Request[pb.GetEducationRequest]) (*connect.Response[pb.Education], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.EducationService.GetEducation is not implemented"))
}

func (UnimplementedEducationServiceHandler) GetEducationsByUser(context.Context, *connect.Request[pb.GetEducationsByUserRequest]) (*connect.Response[pb.ListEducationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.EducationService.GetEducationsByUser is not implemented"))
}

func (UnimplementedEducationServiceHandler) UpdateEducation(context.Context, *connect.Request[pb.UpdateEducationRequest]) (*connect.Response[pb.Education], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.EducationService.UpdateEducation is not implemented"))
}

func (UnimplementedEducationServiceHandler) DeleteEducation(context.Context, *connect.Request[pb.DeleteEducationRequest]) (*connect.Response[pb.EmptyEducationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.EducationService.DeleteEducation is not implemented"))
}

func (UnimplementedEducationServiceHandler) DeleteEducationsByUser(context.Context, *connect.Request[pb.DeleteEducationsByUserRequest]) (*connect.Response[pb.EmptyEducationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.EducationService.DeleteEducationsByUser is not implemented"))
}
