// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: job.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pb "job-service/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// JobServiceName is the fully-qualified name of the JobService service.
	JobServiceName = "pb.JobService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// JobServiceCreateJobProcedure is the fully-qualified name of the JobService's CreateJob RPC.
	JobServiceCreateJobProcedure = "/pb.JobService/CreateJob"
	// JobServiceGetJobProcedure is the fully-qualified name of the JobService's GetJob RPC.
	JobServiceGetJobProcedure = "/pb.JobService/GetJob"
	// JobServiceGetJobsByUserProcedure is the fully-qualified name of the JobService's GetJobsByUser
	// RPC.
	JobServiceGetJobsByUserProcedure = "/pb.JobService/GetJobsByUser"
	// JobServiceUpdateJobProcedure is the fully-qualified name of the JobService's UpdateJob RPC.
	JobServiceUpdateJobProcedure = "/pb.JobService/UpdateJob"
	// JobServiceDeleteJobProcedure is the fully-qualified name of the JobService's DeleteJob RPC.
	JobServiceDeleteJobProcedure = "/pb.JobService/DeleteJob"
	// JobServiceDeleteJobsByUserProcedure is the fully-qualified name of the JobService's
	// DeleteJobsByUser RPC.
	JobServiceDeleteJobsByUserProcedure = "/pb.JobService/DeleteJobsByUser"
)

// JobServiceClient is a client for the pb.JobService service.
type JobServiceClient interface {
	CreateJob(context.Context, *connect.Request[pb.CreateJobRequest]) (*connect.Response[pb.Job], error)
	GetJob(context.Context, *connect.Request[pb.GetJobRequest]) (*connect.Response[pb.Job], error)
	GetJobsByUser(context.Context, *connect.Request[pb.GetJobsByUserRequest]) (*connect.Response[pb.ListJobsResponse], error)
	UpdateJob(context.Context, *connect.Request[pb.UpdateJobRequest]) (*connect.Response[pb.Job], error)
	DeleteJob(context.Context, *connect.Request[pb.DeleteJobRequest]) (*connect.Response[pb.EmptyJobResponse], error)
	DeleteJobsByUser(context.Context, *connect.Request[pb.DeleteJobsByUserRequest]) (*connect.Response[pb.EmptyJobResponse], error)
}

// NewJobServiceClient constructs a client for the pb.JobService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewJobServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) JobServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	jobServiceMethods := pb.File_job_proto.Services().ByName("JobService").Methods()
	return &jobServiceClient{
		createJob: connect.NewClient[pb.CreateJobRequest, pb.Job](
			httpClient,
			baseURL+JobServiceCreateJobProcedure,
			connect.WithSchema(jobServiceMethods.ByName("CreateJob")),
			connect.WithClientOptions(opts...),
		),
		getJob: connect.NewClient[pb.GetJobRequest, pb.Job](
			httpClient,
			baseURL+JobServiceGetJobProcedure,
			connect.WithSchema(jobServiceMethods.ByName("GetJob")),
			connect.WithClientOptions(opts...),
		),
		getJobsByUser: connect.NewClient[pb.GetJobsByUserRequest, pb.ListJobsResponse](
			httpClient,
			baseURL+JobServiceGetJobsByUserProcedure,
			connect.WithSchema(jobServiceMethods.ByName("GetJobsByUser")),
			connect.WithClientOptions(opts...),
		),
		updateJob: connect.NewClient[pb.UpdateJobRequest, pb.Job](
			httpClient,
			baseURL+JobServiceUpdateJobProcedure,
			connect.WithSchema(jobServiceMethods.ByName("UpdateJob")),
			connect.WithClientOptions(opts...),
		),
		deleteJob: connect.NewClient[pb.DeleteJobRequest, pb.EmptyJobResponse](
			httpClient,
			baseURL+JobServiceDeleteJobProcedure,
			connect.WithSchema(jobServiceMethods.ByName("DeleteJob")),
			connect.WithClientOptions(opts...),
		),
		deleteJobsByUser: connect.NewClient[pb.DeleteJobsByUserRequest, pb.EmptyJobResponse](
			httpClient,
			baseURL+JobServiceDeleteJobsByUserProcedure,
			connect.WithSchema(jobServiceMethods.ByName("DeleteJobsByUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// jobServiceClient implements JobServiceClient.
type jobServiceClient struct {
	createJob        *connect.Client[pb.CreateJobRequest, pb.Job]
	getJob           *connect.Client[pb.GetJobRequest, pb.Job]
	getJobsByUser    *connect.Client[pb.GetJobsByUserRequest, pb.ListJobsResponse]
	updateJob        *connect.Client[pb.UpdateJobRequest, pb.Job]
	deleteJob        *connect.Client[pb.DeleteJobRequest, pb.EmptyJobResponse]
	deleteJobsByUser *connect.Client[pb.DeleteJobsByUserRequest, pb.EmptyJobResponse]
}

// CreateJob calls pb.JobService.CreateJob.
func (c *jobServiceClient) CreateJob(ctx context.Context, req *connect.Request[pb.CreateJobRequest]) (*connect.Response[pb.Job], error) {
	return c.createJob.CallUnary(ctx, req)
}

// GetJob calls pb.JobService.GetJob.
func (c *jobServiceClient) GetJob(ctx context.Context, req *connect.Request[pb.GetJobRequest]) (*connect.Response[pb.Job], error) {
	return c.getJob.CallUnary(ctx, req)
}

// GetJobsByUser calls pb.JobService.GetJobsByUser.
func (c *jobServiceClient) GetJobsByUser(ctx context.Context, req *connect.Request[pb.GetJobsByUserRequest]) (*connect.Response[pb.ListJobsResponse], error) {
	return c.getJobsByUser.CallUnary(ctx, req)
}

// UpdateJob calls pb.JobService.UpdateJob.
func (c *jobServiceClient) UpdateJob(ctx context.Context, req *connect.Request[pb.UpdateJobRequest]) (*connect.Response[pb.Job], error) {
	return c.updateJob.CallUnary(ctx, req)
}

// DeleteJob calls pb.JobService.DeleteJob.
func (c *jobServiceClient) DeleteJob(ctx context.Context, req *connect.Request[pb.DeleteJobRequest]) (*connect.Response[pb.EmptyJobResponse], error) {
	return c.deleteJob.CallUnary(ctx, req)
}

// DeleteJobsByUser calls pb.JobService.DeleteJobsByUser.
func (c *jobServiceClient) DeleteJobsByUser(ctx context.Context, req *connect.Request[pb.DeleteJobsByUserRequest]) (*connect.Response[pb.EmptyJobResponse], error) {
	return c.deleteJobsByUser.CallUnary(ctx, req)
}

// JobServiceHandler is an implementation of the pb.JobService service.
type JobServiceHandler interface {
	CreateJob(context.Context, *connect.Request[pb.CreateJobRequest]) (*connect.Response[pb.Job], error)
	GetJob(context.Context, *connect.Request[pb.GetJobRequest]) (*connect.Response[pb.Job], error)
	GetJobsByUser(context.Context, *connect.Request[pb.GetJobsByUserRequest]) (*connect.Response[pb.ListJobsResponse], error)
	UpdateJob(context.Context, *connect.Request[pb.UpdateJobRequest]) (*connect.Response[pb.Job], error)
	DeleteJob(context.Context, *connect.Request[pb.DeleteJobRequest]) (*connect.Response[pb.EmptyJobResponse], error)
	DeleteJobsByUser(context.Context, *connect.Request[pb.DeleteJobsByUserRequest]) (*connect.Response[pb.EmptyJobResponse], error)
}

// NewJobServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewJobServiceHandler(svc JobServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	jobServiceMethods := pb.File_job_proto.Services().ByName("JobService").Methods()
	jobServiceCreateJobHandler := connect.NewUnaryHandler(
		JobServiceCreateJobProcedure,
		svc.CreateJob,
		connect.WithSchema(jobServiceMethods.ByName("CreateJob")),
		connect.WithHandlerOptions(opts...),
	)
	jobServiceGetJobHandler := connect.NewUnaryHandler(
		JobServiceGetJobProcedure,
		svc.GetJob,
		connect.WithSchema(jobServiceMethods.ByName("GetJob")),
		connect.WithHandlerOptions(opts...),
	)
	jobServiceGetJobsByUserHandler := connect.NewUnaryHandler(
		JobServiceGetJobsByUserProcedure,
		svc.GetJobsByUser,
		connect.WithSchema(jobServiceMethods.ByName("GetJobsByUser")),
		connect.WithHandlerOptions(opts...),
	)
	jobServiceUpdateJobHandler := connect.NewUnaryHandler(
		JobServiceUpdateJobProcedure,
		svc.UpdateJob,
		connect.WithSchema(jobServiceMethods.ByName("UpdateJob")),
		connect.WithHandlerOptions(opts...),
	)
	jobServiceDeleteJobHandler := connect.NewUnaryHandler(
		JobServiceDeleteJobProcedure,
		svc.DeleteJob,
		connect.WithSchema(jobServiceMethods.ByName("DeleteJob")),
		connect.WithHandlerOptions(opts...),
	)
	jobServiceDeleteJobsByUserHandler := connect.NewUnaryHandler(
		JobServiceDeleteJobsByUserProcedure,
		svc.DeleteJobsByUser,
		connect.WithSchema(jobServiceMethods.ByName("DeleteJobsByUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pb.JobService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case JobServiceCreateJobProcedure:
			jobServiceCreateJobHandler.ServeHTTP(w, r)
		case JobServiceGetJobProcedure:
			jobServiceGetJobHandler.ServeHTTP(w, r)
		case JobServiceGetJobsByUserProcedure:
			jobServiceGetJobsByUserHandler.ServeHTTP(w, r)
		case JobServiceUpdateJobProcedure:
			jobServiceUpdateJobHandler.ServeHTTP(w, r)
		case JobServiceDeleteJobProcedure:
			jobServiceDeleteJobHandler.ServeHTTP(w, r)
		case JobServiceDeleteJobsByUserProcedure:
			jobServiceDeleteJobsByUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedJobServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedJobServiceHandler struct{}

func (UnimplementedJobServiceHandler) CreateJob(context.Context, *connect.Request[pb.CreateJobRequest]) (*connect.Response[pb.Job], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.JobService.CreateJob is not implemented"))
}

func (UnimplementedJobServiceHandler) GetJob(context.Context, *connect.Request[pb.GetJobRequest]) (*connect.Response[pb.Job], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.JobService.GetJob is not implemented"))
}

func (UnimplementedJobServiceHandler) GetJobsByUser(context.Context, *connect.Request[pb.GetJobsByUserRequest]) (*connect.Response[pb.ListJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.JobService.GetJobsByUser is not implemented"))
}

func (UnimplementedJobServiceHandler) UpdateJob(context.Context, *connect.Request[pb.UpdateJobRequest]) (*connect.Response[pb.Job], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.JobService.UpdateJob is not implemented"))
}

func (UnimplementedJobServiceHandler) DeleteJob(context.Context, *connect.Request[pb.DeleteJobRequest]) (*connect.Response[pb.EmptyJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.JobService.DeleteJob is not implemented"))
}

func (UnimplementedJobServiceHandler) DeleteJobsByUser(context.Context, *connect.Request[pb.DeleteJobsByUserRequest]) (*connect.Response[pb.EmptyJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.JobService.DeleteJobsByUser is not implemented"))
}
